# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/enrichcompany'

module OpenApiSDK
  module Operations

    class ListEnrichCompaniesRequest < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # ID of the connection
      field :connection_id, String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }
      # The domain of the company to search
      field :domain, T.nilable(String), { 'query_param': { 'field_name': 'domain', 'style': 'form', 'explode': true } }
      # The name of the company to search
      field :name, T.nilable(String), { 'query_param': { 'field_name': 'name', 'style': 'form', 'explode': true } }


      sig { params(connection_id: String, domain: T.nilable(String), name: T.nilable(String)).void }
      def initialize(connection_id: nil, domain: nil, name: nil)
        @connection_id = connection_id
        @domain = domain
        @name = name
      end
    end


    class ListEnrichCompaniesResponse < OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # HTTP response status code for this operation
      field :status_code, Integer
      # Successful
      field :enrich_company, T.nilable(Shared::EnrichCompany)
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, T.nilable(Faraday::Response)


      sig { params(content_type: String, status_code: Integer, enrich_company: T.nilable(Shared::EnrichCompany), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, enrich_company: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @enrich_company = enrich_company
        @raw_response = raw_response
      end
    end
  end
end
