# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class AccountingCreditmemoPaymentCollectionMethod < T::Enum


        enums do
          SEND_INVOICE = new('send_invoice')
          CHARGE_AUTOMATICALLY = new('charge_automatically')
        end
      end
    end
  end
end
