# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class AccountType < T::Enum


        enums do
          CHECKING = new('CHECKING')
          SAVINGS = new('SAVINGS')
          CREDIT_CARD = new('CREDIT_CARD')
          LOAN = new('LOAN')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
