# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class AdsAd
        extend T::Sig
        include Crystalline::MetadataFields


        field :ad_copy, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('ad_copy') } }

        field :ad_type, Crystalline::Nilable.new(Models::Shared::AdType), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('ad_type'), 'decoder': Utils.enum_from_string(Models::Shared::AdType, true) } }

        field :campaign_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('campaign_id') } }

        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :creative_asset_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('creative_asset_url') } }

        field :creative_ids, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('creative_ids') } }

        field :cta, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('cta') } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('description') } }

        field :display_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('display_url') } }

        field :end_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('end_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :final_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('final_url') } }

        field :group_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('group_id') } }

        field :headline, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('headline') } }

        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('id') } }

        field :is_active, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('is_active') } }

        field :item_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('item_id') } }

        field :metadata, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::AdsMetadata)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('metadata') } }

        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('name') } }

        field :organization_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('organization_id') } }

        field :path1, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('path1') } }

        field :path2, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('path2') } }

        field :raw, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('raw') } }

        field :start_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('start_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :status, Crystalline::Nilable.new(Models::Shared::AdsAdStatus), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Shared::AdsAdStatus, true) } }

        field :targeting, Crystalline::Nilable.new(Models::Shared::PropertyAdsAdTargeting), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('targeting') } }

        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        sig { params(ad_copy: T.nilable(::String), ad_type: T.nilable(Models::Shared::AdType), campaign_id: T.nilable(::String), created_at: T.nilable(::DateTime), creative_asset_url: T.nilable(::String), creative_ids: T.nilable(T::Array[::String]), cta: T.nilable(::String), description: T.nilable(::String), display_url: T.nilable(::String), end_at: T.nilable(::DateTime), final_url: T.nilable(::String), group_id: T.nilable(::String), headline: T.nilable(::String), id: T.nilable(::String), is_active: T.nilable(T::Boolean), item_id: T.nilable(::String), metadata: T.nilable(T::Array[Models::Shared::AdsMetadata]), name: T.nilable(::String), organization_id: T.nilable(::String), path1: T.nilable(::String), path2: T.nilable(::String), raw: T.nilable(T::Hash[Symbol, ::Object]), start_at: T.nilable(::DateTime), status: T.nilable(Models::Shared::AdsAdStatus), targeting: T.nilable(Models::Shared::PropertyAdsAdTargeting), updated_at: T.nilable(::DateTime)).void }
        def initialize(ad_copy: nil, ad_type: nil, campaign_id: nil, created_at: nil, creative_asset_url: nil, creative_ids: nil, cta: nil, description: nil, display_url: nil, end_at: nil, final_url: nil, group_id: nil, headline: nil, id: nil, is_active: nil, item_id: nil, metadata: nil, name: nil, organization_id: nil, path1: nil, path2: nil, raw: nil, start_at: nil, status: nil, targeting: nil, updated_at: nil)
          @ad_copy = ad_copy
          @ad_type = ad_type
          @campaign_id = campaign_id
          @created_at = created_at
          @creative_asset_url = creative_asset_url
          @creative_ids = creative_ids
          @cta = cta
          @description = description
          @display_url = display_url
          @end_at = end_at
          @final_url = final_url
          @group_id = group_id
          @headline = headline
          @id = id
          @is_active = is_active
          @item_id = item_id
          @metadata = metadata
          @name = name
          @organization_id = organization_id
          @path1 = path1
          @path2 = path2
          @raw = raw
          @start_at = start_at
          @status = status
          @targeting = targeting
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @ad_copy == other.ad_copy
          return false unless @ad_type == other.ad_type
          return false unless @campaign_id == other.campaign_id
          return false unless @created_at == other.created_at
          return false unless @creative_asset_url == other.creative_asset_url
          return false unless @creative_ids == other.creative_ids
          return false unless @cta == other.cta
          return false unless @description == other.description
          return false unless @display_url == other.display_url
          return false unless @end_at == other.end_at
          return false unless @final_url == other.final_url
          return false unless @group_id == other.group_id
          return false unless @headline == other.headline
          return false unless @id == other.id
          return false unless @is_active == other.is_active
          return false unless @item_id == other.item_id
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          return false unless @organization_id == other.organization_id
          return false unless @path1 == other.path1
          return false unless @path2 == other.path2
          return false unless @raw == other.raw
          return false unless @start_at == other.start_at
          return false unless @status == other.status
          return false unless @targeting == other.targeting
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
