# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class AdsInsertionorderBudgetUnit < T::Enum


        enums do
          UNSPECIFIED = new('UNSPECIFIED')
          CURRENCY = new('CURRENCY')
          IMPRESSIONS = new('IMPRESSIONS')
        end
      end
    end
  end
end
