# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class AdsTargetType < T::Enum


        enums do
          INTERESTS = new('INTERESTS')
          BEHAVIORS = new('BEHAVIORS')
          LOCALES = new('LOCALES')
          COUNTRIES = new('COUNTRIES')
          REGIONS = new('REGIONS')
          CITIES = new('CITIES')
          ZIPS = new('ZIPS')
          US_DMAS = new('US_DMAS')
          TOPICS = new('TOPICS')
          USER_LISTS = new('USER_LISTS')
          AGE_RANGES = new('AGE_RANGES')
          GENDERS = new('GENDERS')
        end
      end
    end
  end
end
