# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class AssessmentParameterInput
        extend T::Sig
        include Crystalline::MetadataFields


        field :inputs, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('inputs') } }

        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('name') } }

        field :parameter_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('parameter_id') } }

        sig { params(inputs: T.nilable(T::Array[::String]), name: T.nilable(::String), parameter_id: T.nilable(::String)).void }
        def initialize(inputs: nil, name: nil, parameter_id: nil)
          @inputs = inputs
          @name = name
          @parameter_id = parameter_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @inputs == other.inputs
          return false unless @name == other.name
          return false unless @parameter_id == other.parameter_id
          true
        end
      end
    end
  end
end
