# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class CalendarWebinarRegistrant
        extend T::Sig
        include Crystalline::MetadataFields


        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('email') } }

        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('name') } }

        field :registered_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('registered_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :registration_reference, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('registration_reference') } }

        field :registration_status, Crystalline::Nilable.new(Models::Shared::RegistrationStatus), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('registration_status'), 'decoder': Utils.enum_from_string(Models::Shared::RegistrationStatus, true) } }

        sig { params(email: T.nilable(::String), name: T.nilable(::String), registered_at: T.nilable(::DateTime), registration_reference: T.nilable(::String), registration_status: T.nilable(Models::Shared::RegistrationStatus)).void }
        def initialize(email: nil, name: nil, registered_at: nil, registration_reference: nil, registration_status: nil)
          @email = email
          @name = name
          @registered_at = registered_at
          @registration_reference = registration_reference
          @registration_status = registration_status
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @email == other.email
          return false unless @name == other.name
          return false unless @registered_at == other.registered_at
          return false unless @registration_reference == other.registration_reference
          return false unless @registration_status == other.registration_status
          true
        end
      end
    end
  end
end
