# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class DatastoreTable
        extend T::Sig
        include Crystalline::MetadataFields


        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :database_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('database_id') } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('description') } }

        field :fields_, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::DatastoreField)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('fields') } }

        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('id') } }

        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('name') } }

        field :parent_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('parent_id') } }

        field :raw, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('raw') } }

        field :relationships, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::DatastoreRelationship)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('relationships') } }

        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :web_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('web_url') } }

        sig { params(created_at: T.nilable(::DateTime), database_id: T.nilable(::String), description: T.nilable(::String), fields_: T.nilable(T::Array[Models::Shared::DatastoreField]), id: T.nilable(::String), name: T.nilable(::String), parent_id: T.nilable(::String), raw: T.nilable(T::Hash[Symbol, ::Object]), relationships: T.nilable(T::Array[Models::Shared::DatastoreRelationship]), updated_at: T.nilable(::DateTime), web_url: T.nilable(::String)).void }
        def initialize(created_at: nil, database_id: nil, description: nil, fields_: nil, id: nil, name: nil, parent_id: nil, raw: nil, relationships: nil, updated_at: nil, web_url: nil)
          @created_at = created_at
          @database_id = database_id
          @description = description
          @fields_ = fields_
          @id = id
          @name = name
          @parent_id = parent_id
          @raw = raw
          @relationships = relationships
          @updated_at = updated_at
          @web_url = web_url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @created_at == other.created_at
          return false unless @database_id == other.database_id
          return false unless @description == other.description
          return false unless @fields_ == other.fields_
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @parent_id == other.parent_id
          return false unless @raw == other.raw
          return false unless @relationships == other.relationships
          return false unless @updated_at == other.updated_at
          return false unless @web_url == other.web_url
          true
        end
      end
    end
  end
end
