# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class DbType < T::Enum
        enums do
          MONGODB = new('mongodb')
          MYSQL = new('mysql')
          POSTGRES = new('postgres')
          MSSQL = new('mssql')
          MARIADB = new('mariadb')
        end
      end
    end
  end
end
