# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class HrisTimeoffType < T::Enum


        enums do
          VACATION = new('VACATION')
          SICK = new('SICK')
          HOLIDAY = new('HOLIDAY')
          BEREAVEMENT = new('BEREAVEMENT')
          PARENTAL = new('PARENTAL')
          UNPAID = new('UNPAID')
          IN_LIEU = new('IN_LIEU')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
