# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class NonDeliveryOption < T::Enum


        enums do
          RETURN = new('RETURN')
          ABANDON = new('ABANDON')
        end
      end
    end
  end
end
