# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class PaymentAllocation
        extend T::Sig
        include Crystalline::MetadataFields


        field :allocated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('allocated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('amount') } }

        field :currency, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('currency') } }

        field :exchange_rate, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('exchange_rate') } }

        field :object_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('object_id') } }

        field :object_type, Crystalline::Nilable.new(Models::Shared::PaymentAllocationObjectType), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('object_type'), 'decoder': Utils.enum_from_string(Models::Shared::PaymentAllocationObjectType, true) } }

        sig { params(allocated_at: T.nilable(::DateTime), amount: T.nilable(::Float), currency: T.nilable(::String), exchange_rate: T.nilable(::Float), object_id: T.nilable(::String), object_type: T.nilable(Models::Shared::PaymentAllocationObjectType)).void }
        def initialize(allocated_at: nil, amount: nil, currency: nil, exchange_rate: nil, object_id: nil, object_type: nil)
          @allocated_at = allocated_at
          @amount = amount
          @currency = currency
          @exchange_rate = exchange_rate
          @object_id = object_id
          @object_type = object_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @allocated_at == other.allocated_at
          return false unless @amount == other.amount
          return false unless @currency == other.currency
          return false unless @exchange_rate == other.exchange_rate
          return false unless @object_id == other.object_id
          return false unless @object_type == other.object_type
          true
        end
      end
    end
  end
end
