# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class PaymentAllocationObjectType < T::Enum


        enums do
          INVOICE = new('INVOICE')
          BILL = new('BILL')
          CREDITMEMO = new('CREDITMEMO')
          VENDORCREDIT = new('VENDORCREDIT')
          SALESORDER = new('SALESORDER')
          PURCHASEORDER = new('PURCHASEORDER')
        end
      end
    end
  end
end
