# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class PropertyAdsReportMetricsGroupCreativeSelection < T::Enum


        enums do
          OPTIMIZED = new('OPTIMIZED')
          ROUND_ROBIN = new('ROUND_ROBIN')
        end
      end
    end
  end
end
