# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class PropertyAdsReportMetricsCampaignFrequencyCapTimeUnit < T::Enum


        enums do
          UNSPECIFIED = new('UNSPECIFIED')
          LIFETIME = new('LIFETIME')
          MONTHS = new('MONTHS')
          WEEKS = new('WEEKS')
          DAYS = new('DAYS')
          HOURS = new('HOURS')
          MINUTES = new('MINUTES')
        end
      end
    end
  end
end
