# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class PropertyAdsGroupPacing
        extend T::Sig
        include Crystalline::MetadataFields


        field :daily_max_amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('daily_max_amount') } }

        field :daily_max_impressions, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('daily_max_impressions') } }

        field :period, Crystalline::Nilable.new(Models::Shared::Period), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('period'), 'decoder': Utils.enum_from_string(Models::Shared::Period, true) } }

        field :type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('type') } }

        sig { params(daily_max_amount: T.nilable(::Float), daily_max_impressions: T.nilable(::Float), period: T.nilable(Models::Shared::Period), type: T.nilable(::String)).void }
        def initialize(daily_max_amount: nil, daily_max_impressions: nil, period: nil, type: nil)
          @daily_max_amount = daily_max_amount
          @daily_max_impressions = daily_max_impressions
          @period = period
          @type = type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @daily_max_amount == other.daily_max_amount
          return false unless @daily_max_impressions == other.daily_max_impressions
          return false unless @period == other.period
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
