# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class ReturnType < T::Enum


        enums do
          CUSTOMER = new('CUSTOMER')
          VENDOR = new('VENDOR')
          WARRANTY = new('WARRANTY')
          DEFECTIVE = new('DEFECTIVE')
          OTHER = new('OTHER')
        end
      end
    end
  end
end
