# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class ShippingCarrier
        extend T::Sig
        include Crystalline::MetadataFields


        field :code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('code') } }

        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('id') } }

        field :is_active, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('is_active') } }

        field :logo_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('logo_url') } }

        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('name') } }

        field :raw, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('raw') } }

        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :website_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('website_url') } }

        sig { params(code: T.nilable(::String), created_at: T.nilable(::DateTime), id: T.nilable(::String), is_active: T.nilable(T::Boolean), logo_url: T.nilable(::String), name: T.nilable(::String), raw: T.nilable(T::Hash[Symbol, ::Object]), updated_at: T.nilable(::DateTime), website_url: T.nilable(::String)).void }
        def initialize(code: nil, created_at: nil, id: nil, is_active: nil, logo_url: nil, name: nil, raw: nil, updated_at: nil, website_url: nil)
          @code = code
          @created_at = created_at
          @id = id
          @is_active = is_active
          @logo_url = logo_url
          @name = name
          @raw = raw
          @updated_at = updated_at
          @website_url = website_url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @code == other.code
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @is_active == other.is_active
          return false unless @logo_url == other.logo_url
          return false unless @name == other.name
          return false unless @raw == other.raw
          return false unless @updated_at == other.updated_at
          return false unless @website_url == other.website_url
          true
        end
      end
    end
  end
end
