# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class ShippingShipment
        extend T::Sig
        include Crystalline::MetadataFields


        field :carrier_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('carrier_id') } }

        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # Customs information
        field :customs, Crystalline::Nilable.new(Models::Shared::PropertyShippingShipmentCustoms), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('customs') } }
        # Origin address
        field :from_address, Crystalline::Nilable.new(Models::Shared::PropertyShippingShipmentFromAddress), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('from_address') } }

        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('id') } }
        # Insurance details
        field :insurance, Crystalline::Nilable.new(Models::Shared::PropertyShippingShipmentInsurance), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('insurance') } }

        field :is_adult_signature_required, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('is_adult_signature_required') } }

        field :is_international, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('is_international') } }

        field :is_rate_guaranteed, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('is_rate_guaranteed') } }

        field :is_return, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('is_return') } }

        field :is_signature_required, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('is_signature_required') } }

        field :label_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('label_id') } }

        field :order_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('order_id') } }

        field :original_shipment_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('original_shipment_id') } }
        # Array of packages in this shipment
        field :packages, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::ShippingPackage)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('packages') } }

        field :rate_amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('rate_amount') } }

        field :rate_currency, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('rate_currency') } }

        field :rate_estimated_days, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('rate_estimated_days') } }

        field :rate_estimated_delivery_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('rate_estimated_delivery_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :rate_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('rate_id') } }

        field :rate_service_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('rate_service_name') } }

        field :raw, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('raw') } }

        field :reference_number, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('reference_number') } }
        # Return address (may differ from from_address)
        field :return_address, Crystalline::Nilable.new(Models::Shared::PropertyShippingShipmentReturnAddress), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('return_address') } }

        field :return_authorization_number, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('return_authorization_number') } }

        field :return_reason, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('return_reason') } }

        field :return_type, Crystalline::Nilable.new(Models::Shared::ReturnType), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('return_type'), 'decoder': Utils.enum_from_string(Models::Shared::ReturnType, true) } }

        field :service_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('service_code') } }

        field :shipped_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('shipped_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # Array of special instructions
        field :special_instructions, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('special_instructions') } }

        field :status, Crystalline::Nilable.new(Models::Shared::ShippingShipmentStatus), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Shared::ShippingShipmentStatus, true) } }
        # Destination address
        field :to_address, Crystalline::Nilable.new(Models::Shared::PropertyShippingShipmentToAddress), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('to_address') } }

        field :tracking_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('tracking_id') } }

        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :warehouse_location_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('warehouse_location_id') } }

        field :warehouse_location_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('warehouse_location_name') } }

        sig { params(carrier_id: T.nilable(::String), created_at: T.nilable(::DateTime), customs: T.nilable(Models::Shared::PropertyShippingShipmentCustoms), from_address: T.nilable(Models::Shared::PropertyShippingShipmentFromAddress), id: T.nilable(::String), insurance: T.nilable(Models::Shared::PropertyShippingShipmentInsurance), is_adult_signature_required: T.nilable(T::Boolean), is_international: T.nilable(T::Boolean), is_rate_guaranteed: T.nilable(T::Boolean), is_return: T.nilable(T::Boolean), is_signature_required: T.nilable(T::Boolean), label_id: T.nilable(::String), order_id: T.nilable(::String), original_shipment_id: T.nilable(::String), packages: T.nilable(T::Array[Models::Shared::ShippingPackage]), rate_amount: T.nilable(::Float), rate_currency: T.nilable(::String), rate_estimated_days: T.nilable(::Float), rate_estimated_delivery_at: T.nilable(::DateTime), rate_id: T.nilable(::String), rate_service_name: T.nilable(::String), raw: T.nilable(T::Hash[Symbol, ::Object]), reference_number: T.nilable(::String), return_address: T.nilable(Models::Shared::PropertyShippingShipmentReturnAddress), return_authorization_number: T.nilable(::String), return_reason: T.nilable(::String), return_type: T.nilable(Models::Shared::ReturnType), service_code: T.nilable(::String), shipped_at: T.nilable(::DateTime), special_instructions: T.nilable(T::Array[::String]), status: T.nilable(Models::Shared::ShippingShipmentStatus), to_address: T.nilable(Models::Shared::PropertyShippingShipmentToAddress), tracking_id: T.nilable(::String), updated_at: T.nilable(::DateTime), warehouse_location_id: T.nilable(::String), warehouse_location_name: T.nilable(::String)).void }
        def initialize(carrier_id: nil, created_at: nil, customs: nil, from_address: nil, id: nil, insurance: nil, is_adult_signature_required: nil, is_international: nil, is_rate_guaranteed: nil, is_return: nil, is_signature_required: nil, label_id: nil, order_id: nil, original_shipment_id: nil, packages: nil, rate_amount: nil, rate_currency: nil, rate_estimated_days: nil, rate_estimated_delivery_at: nil, rate_id: nil, rate_service_name: nil, raw: nil, reference_number: nil, return_address: nil, return_authorization_number: nil, return_reason: nil, return_type: nil, service_code: nil, shipped_at: nil, special_instructions: nil, status: nil, to_address: nil, tracking_id: nil, updated_at: nil, warehouse_location_id: nil, warehouse_location_name: nil)
          @carrier_id = carrier_id
          @created_at = created_at
          @customs = customs
          @from_address = from_address
          @id = id
          @insurance = insurance
          @is_adult_signature_required = is_adult_signature_required
          @is_international = is_international
          @is_rate_guaranteed = is_rate_guaranteed
          @is_return = is_return
          @is_signature_required = is_signature_required
          @label_id = label_id
          @order_id = order_id
          @original_shipment_id = original_shipment_id
          @packages = packages
          @rate_amount = rate_amount
          @rate_currency = rate_currency
          @rate_estimated_days = rate_estimated_days
          @rate_estimated_delivery_at = rate_estimated_delivery_at
          @rate_id = rate_id
          @rate_service_name = rate_service_name
          @raw = raw
          @reference_number = reference_number
          @return_address = return_address
          @return_authorization_number = return_authorization_number
          @return_reason = return_reason
          @return_type = return_type
          @service_code = service_code
          @shipped_at = shipped_at
          @special_instructions = special_instructions
          @status = status
          @to_address = to_address
          @tracking_id = tracking_id
          @updated_at = updated_at
          @warehouse_location_id = warehouse_location_id
          @warehouse_location_name = warehouse_location_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @carrier_id == other.carrier_id
          return false unless @created_at == other.created_at
          return false unless @customs == other.customs
          return false unless @from_address == other.from_address
          return false unless @id == other.id
          return false unless @insurance == other.insurance
          return false unless @is_adult_signature_required == other.is_adult_signature_required
          return false unless @is_international == other.is_international
          return false unless @is_rate_guaranteed == other.is_rate_guaranteed
          return false unless @is_return == other.is_return
          return false unless @is_signature_required == other.is_signature_required
          return false unless @label_id == other.label_id
          return false unless @order_id == other.order_id
          return false unless @original_shipment_id == other.original_shipment_id
          return false unless @packages == other.packages
          return false unless @rate_amount == other.rate_amount
          return false unless @rate_currency == other.rate_currency
          return false unless @rate_estimated_days == other.rate_estimated_days
          return false unless @rate_estimated_delivery_at == other.rate_estimated_delivery_at
          return false unless @rate_id == other.rate_id
          return false unless @rate_service_name == other.rate_service_name
          return false unless @raw == other.raw
          return false unless @reference_number == other.reference_number
          return false unless @return_address == other.return_address
          return false unless @return_authorization_number == other.return_authorization_number
          return false unless @return_reason == other.return_reason
          return false unless @return_type == other.return_type
          return false unless @service_code == other.service_code
          return false unless @shipped_at == other.shipped_at
          return false unless @special_instructions == other.special_instructions
          return false unless @status == other.status
          return false unless @to_address == other.to_address
          return false unless @tracking_id == other.tracking_id
          return false unless @updated_at == other.updated_at
          return false unless @warehouse_location_id == other.warehouse_location_id
          return false unless @warehouse_location_name == other.warehouse_location_name
          true
        end
      end
    end
  end
end
