# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class SigningDocument
        extend T::Sig
        include Crystalline::MetadataFields


        field :completed_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('completed_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :creator_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('creator_id') } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('description') } }

        field :download_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('download_url') } }

        field :expires_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('expires_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('id') } }
        # Custom key-value pairs
        field :metadata, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::String)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('metadata') } }

        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('name') } }

        field :raw, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('raw') } }

        field :sent_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('sent_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :status, Crystalline::Nilable.new(Models::Shared::SigningDocumentStatus), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Shared::SigningDocumentStatus, true) } }

        field :template_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('template_id') } }

        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::UnifiedRubySDK::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        sig { params(completed_at: T.nilable(::DateTime), created_at: T.nilable(::DateTime), creator_id: T.nilable(::String), description: T.nilable(::String), download_url: T.nilable(::String), expires_at: T.nilable(::DateTime), id: T.nilable(::String), metadata: T.nilable(T::Hash[Symbol, ::String]), name: T.nilable(::String), raw: T.nilable(T::Hash[Symbol, ::Object]), sent_at: T.nilable(::DateTime), status: T.nilable(Models::Shared::SigningDocumentStatus), template_id: T.nilable(::String), updated_at: T.nilable(::DateTime)).void }
        def initialize(completed_at: nil, created_at: nil, creator_id: nil, description: nil, download_url: nil, expires_at: nil, id: nil, metadata: nil, name: nil, raw: nil, sent_at: nil, status: nil, template_id: nil, updated_at: nil)
          @completed_at = completed_at
          @created_at = created_at
          @creator_id = creator_id
          @description = description
          @download_url = download_url
          @expires_at = expires_at
          @id = id
          @metadata = metadata
          @name = name
          @raw = raw
          @sent_at = sent_at
          @status = status
          @template_id = template_id
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @completed_at == other.completed_at
          return false unless @created_at == other.created_at
          return false unless @creator_id == other.creator_id
          return false unless @description == other.description
          return false unless @download_url == other.download_url
          return false unless @expires_at == other.expires_at
          return false unless @id == other.id
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          return false unless @raw == other.raw
          return false unless @sent_at == other.sent_at
          return false unless @status == other.status
          return false unless @template_id == other.template_id
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
