# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class SizeUnit < T::Enum


        enums do
          CM = new('cm')
          INCH = new('inch')
        end
      end
    end
  end
end
