# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Shared
    

      class Term < T::Enum


        enums do
          ON_RECEIPT = new('ON_RECEIPT')
          NET_7 = new('NET_7')
          NET_10 = new('NET_10')
          NET_15 = new('NET_15')
          NET_20 = new('NET_20')
          NET_25 = new('NET_25')
          NET_30 = new('NET_30')
          NET_60 = new('NET_60')
        end
      end
    end
  end
end
