# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Operations
  

    class CreateTicketingNoteRequest < ::UnifiedRubySDK::Utils::FieldAugmented
      extend T::Sig

      # ID of the connection
      field :connection_id, ::String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }

      field :ticketing_note, T.nilable(::UnifiedRubySDK::Shared::TicketingNote), { 'request': { 'media_type': 'application/json' } }


      sig { params(connection_id: ::String, ticketing_note: T.nilable(::UnifiedRubySDK::Shared::TicketingNote)).void }
      def initialize(connection_id: nil, ticketing_note: nil)
        @connection_id = connection_id
        @ticketing_note = ticketing_note
      end
    end
  end
end
