# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class CreateShippingRateQueryParamFields < T::Enum


        enums do
          SHIPMENT_ID = new('shipment_id')
          CURRENCY = new('currency')
          FROM_ADDRESS = new('from_address')
          TO_ADDRESS = new('to_address')
          PACKAGES = new('packages')
          SHIP_BY_AT = new('ship_by_at')
          CARRIER_ID = new('carrier_id')
          ID = new('id')
          RATES = new('rates')
          RAW = new('raw')
        end
      end
    end
  end
end
