# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Operations
  

    class CreateGenaiPromptRequest < ::UnifiedRubySDK::Utils::FieldAugmented
      extend T::Sig

      # ID of the connection
      field :connection_id, ::String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }

      field :genai_prompt, T.nilable(::UnifiedRubySDK::Shared::GenaiPrompt), { 'request': { 'media_type': 'application/json' } }


      sig { params(connection_id: ::String, genai_prompt: T.nilable(::UnifiedRubySDK::Shared::GenaiPrompt)).void }
      def initialize(connection_id: nil, genai_prompt: nil)
        @connection_id = connection_id
        @genai_prompt = genai_prompt
      end
    end
  end
end
