# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class CreateAdsGroupRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :ads_group, Models::Shared::AdsGroup, { 'request': { 'media_type': 'application/json' } }
        # ID of the connection
        field :connection_id, ::String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }
        # Fields to return
        field :fields_, Crystalline::Nilable.new(Crystalline::Array.new(Models::Operations::CreateAdsGroupQueryParamFields)), { 'query_param': { 'field_name': 'fields', 'style': 'form', 'explode': true } }
        # Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
        field :raw, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'raw', 'style': 'form', 'explode': true } }

        sig { params(ads_group: Models::Shared::AdsGroup, connection_id: ::String, fields_: T.nilable(T::Array[Models::Operations::CreateAdsGroupQueryParamFields]), raw: T.nilable(::String)).void }
        def initialize(ads_group:, connection_id:, fields_: nil, raw: nil)
          @ads_group = ads_group
          @connection_id = connection_id
          @fields_ = fields_
          @raw = raw
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @ads_group == other.ads_group
          return false unless @connection_id == other.connection_id
          return false unless @fields_ == other.fields_
          return false unless @raw == other.raw
          true
        end
      end
    end
  end
end
