# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class CreateTicketingTicketRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of the connection
        field :connection_id, ::String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }

        field :ticketing_ticket, Models::Shared::TicketingTicket, { 'request': { 'media_type': 'application/json' } }
        # Comma-delimited fields to return
        field :fields_, T.nilable(T::Array[::String]), { 'query_param': { 'field_name': 'fields', 'style': 'form', 'explode': true } }


        sig { params(connection_id: ::String, ticketing_ticket: Models::Shared::TicketingTicket, fields_: T.nilable(T::Array[::String])).void }
        def initialize(connection_id: nil, ticketing_ticket: nil, fields_: nil)
          @connection_id = connection_id
          @ticketing_ticket = ticketing_ticket
          @fields_ = fields_
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @connection_id == other.connection_id
          return false unless @ticketing_ticket == other.ticketing_ticket
          return false unless @fields_ == other.fields_
          true
        end
      end
    end
  end
end
