# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class GetAtsApplicationQueryParamFields < T::Enum


        enums do
          ID = new('id')
          CANDIDATE_ID = new('candidate_id')
          JOB_ID = new('job_id')
          CREATED_AT = new('created_at')
          UPDATED_AT = new('updated_at')
          APPLIED_AT = new('applied_at')
          HIRED_AT = new('hired_at')
          REJECTED_AT = new('rejected_at')
          REJECTED_REASON = new('rejected_reason')
          SOURCE = new('source')
          STATUS = new('status')
          ORIGINAL_STATUS = new('original_status')
          ANSWERS = new('answers')
          OFFERS = new('offers')
          USER_ID = new('user_id')
          METADATA = new('metadata')
          RAW = new('raw')
        end
      end
    end
  end
end
