# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class ListRepoBranchesQueryParamFields < T::Enum


        enums do
          ID = new('id')
          CREATED_AT = new('created_at')
          UPDATED_AT = new('updated_at')
          NAME = new('name')
          REPO_ID = new('repo_id')
          RAW = new('raw')
        end
      end
    end
  end
end
