# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class ListStorageFilesQueryParamFields < T::Enum


        enums do
          ID = new('id')
          CREATED_AT = new('created_at')
          UPDATED_AT = new('updated_at')
          NAME = new('name')
          DESCRIPTION = new('description')
          PARENT_ID = new('parent_id')
          USER_ID = new('user_id')
          SIZE = new('size')
          TYPE = new('type')
          MIME_TYPE = new('mime_type')
          PERMISSIONS = new('permissions')
          DOWNLOAD_URL = new('download_url')
          HASH = new('hash')
          DATA = new('data')
          VERSION = new('version')
          WEB_URL = new('web_url')
          RAW = new('raw')
        end
      end
    end
  end
end
