# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class ListAtsActivitiesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of the connection
        field :connection_id, ::String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }
        # The application ID to filter by
        field :application_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'application_id', 'style': 'form', 'explode': true } }
        # The candidate ID to filter by
        field :candidate_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'candidate_id', 'style': 'form', 'explode': true } }
        # The document ID to filter by
        field :document_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'document_id', 'style': 'form', 'explode': true } }
        # Fields to return
        field :fields_, Crystalline::Nilable.new(Crystalline::Array.new(Models::Operations::ListAtsActivitiesQueryParamFields)), { 'query_param': { 'field_name': 'fields', 'style': 'form', 'explode': true } }
        # The interview ID to filter by
        field :interview_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'interview_id', 'style': 'form', 'explode': true } }
        # The job ID to filter by
        field :job_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'job_id', 'style': 'form', 'explode': true } }

        field :limit, Crystalline::Nilable.new(::Float), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }

        field :offset, Crystalline::Nilable.new(::Float), { 'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': true } }

        field :order, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'order', 'style': 'form', 'explode': true } }
        # Query string to search. eg. email address or name
        field :query, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'query', 'style': 'form', 'explode': true } }
        # Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
        field :raw, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'raw', 'style': 'form', 'explode': true } }

        field :sort, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'sort', 'style': 'form', 'explode': true } }
        # The type to filter by
        field :type, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'type', 'style': 'form', 'explode': true } }
        # Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
        field :updated_gte, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'updated_gte', 'style': 'form', 'explode': true } }
        # The user/employee ID to filter by (reference to HrisEmployee)
        field :user_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'user_id', 'style': 'form', 'explode': true } }

        sig { params(connection_id: ::String, application_id: T.nilable(::String), candidate_id: T.nilable(::String), document_id: T.nilable(::String), fields_: T.nilable(T::Array[Models::Operations::ListAtsActivitiesQueryParamFields]), interview_id: T.nilable(::String), job_id: T.nilable(::String), limit: T.nilable(::Float), offset: T.nilable(::Float), order: T.nilable(::String), query: T.nilable(::String), raw: T.nilable(::String), sort: T.nilable(::String), type: T.nilable(::String), updated_gte: T.nilable(::String), user_id: T.nilable(::String)).void }
        def initialize(connection_id:, application_id: nil, candidate_id: nil, document_id: nil, fields_: nil, interview_id: nil, job_id: nil, limit: nil, offset: nil, order: nil, query: nil, raw: nil, sort: nil, type: nil, updated_gte: nil, user_id: nil)
          @connection_id = connection_id
          @application_id = application_id
          @candidate_id = candidate_id
          @document_id = document_id
          @fields_ = fields_
          @interview_id = interview_id
          @job_id = job_id
          @limit = limit
          @offset = offset
          @order = order
          @query = query
          @raw = raw
          @sort = sort
          @type = type
          @updated_gte = updated_gte
          @user_id = user_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @connection_id == other.connection_id
          return false unless @application_id == other.application_id
          return false unless @candidate_id == other.candidate_id
          return false unless @document_id == other.document_id
          return false unless @fields_ == other.fields_
          return false unless @interview_id == other.interview_id
          return false unless @job_id == other.job_id
          return false unless @limit == other.limit
          return false unless @offset == other.offset
          return false unless @order == other.order
          return false unless @query == other.query
          return false unless @raw == other.raw
          return false unless @sort == other.sort
          return false unless @type == other.type
          return false unless @updated_gte == other.updated_gte
          return false unless @user_id == other.user_id
          true
        end
      end
    end
  end
end
