# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class ListHrisPayslipsQueryParamFields < T::Enum


        enums do
          ID = new('id')
          CREATED_AT = new('created_at')
          UPDATED_AT = new('updated_at')
          USER_ID = new('user_id')
          COMPANY_ID = new('company_id')
          PAYMENT_TYPE = new('payment_type')
          PAID_AT = new('paid_at')
          START_AT = new('start_at')
          END_AT = new('end_at')
          CURRENCY = new('currency')
          GROSS_AMOUNT = new('gross_amount')
          NET_AMOUNT = new('net_amount')
          DETAILS = new('details')
          RAW = new('raw')
          DEDUCTION = new('deduction')
        end
      end
    end
  end
end
