# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class PatchCrmDealQueryParamFields < T::Enum


        enums do
          ID = new('id')
          CREATED_AT = new('created_at')
          UPDATED_AT = new('updated_at')
          NAME = new('name')
          AMOUNT = new('amount')
          CURRENCY = new('currency')
          CLOSED_AT = new('closed_at')
          CLOSING_AT = new('closing_at')
          STAGE = new('stage')
          STAGE_ID = new('stage_id')
          PIPELINE = new('pipeline')
          PIPELINE_ID = new('pipeline_id')
          STAGES = new('stages')
          SOURCE = new('source')
          PROBABILITY = new('probability')
          TAGS = new('tags')
          LOST_REASON = new('lost_reason')
          WON_REASON = new('won_reason')
          USER_ID = new('user_id')
          CONTACT_IDS = new('contact_ids')
          COMPANY_IDS = new('company_ids')
          METADATA = new('metadata')
          RAW = new('raw')
          PIPELINES = new('pipelines')
        end
      end
    end
  end
end
