# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Operations
  

    class RemovePassthroughRequest < ::UnifiedRubySDK::Utils::FieldAugmented
      extend T::Sig

      # ID of the connection
      field :connection_id, ::String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }

      field :path, ::String, { 'path_param': { 'field_name': 'path', 'style': 'simple', 'explode': false } }


      sig { params(connection_id: ::String, path: ::String).void }
      def initialize(connection_id: nil, path: nil)
        @connection_id = connection_id
        @path = path
      end
    end
  end
end
