# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class UpdateCrmEventRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # An event represents an event, activity, or engagement and is always associated with a deal, contact, or company
        field :crm_event, Models::Shared::CrmEvent, { 'request': { 'media_type': 'application/json' } }
        # ID of the connection
        field :connection_id, ::String, { 'path_param': { 'field_name': 'connection_id', 'style': 'simple', 'explode': false } }
        # ID of the Event
        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
        # Fields to return
        field :fields_, Crystalline::Nilable.new(Crystalline::Array.new(Models::Operations::UpdateCrmEventQueryParamFields)), { 'query_param': { 'field_name': 'fields', 'style': 'form', 'explode': true } }
        # Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
        field :raw, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'raw', 'style': 'form', 'explode': true } }

        sig { params(crm_event: Models::Shared::CrmEvent, connection_id: ::String, id: ::String, fields_: T.nilable(T::Array[Models::Operations::UpdateCrmEventQueryParamFields]), raw: T.nilable(::String)).void }
        def initialize(crm_event:, connection_id:, id:, fields_: nil, raw: nil)
          @crm_event = crm_event
          @connection_id = connection_id
          @id = id
          @fields_ = fields_
          @raw = raw
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @crm_event == other.crm_event
          return false unless @connection_id == other.connection_id
          return false unless @id == other.id
          return false unless @fields_ == other.fields_
          return false unless @raw == other.raw
          true
        end
      end
    end
  end
end
