# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module UnifiedRubySDK
  module Models
    module Operations
    

      class UpdateUnifiedWebhookRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of the Webhook
        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
        # A webhook is used to POST new/updated information to your server.
        field :webhook, Models::Shared::Webhook, { 'request': { 'media_type': 'application/json' } }


        sig { params(id: ::String, webhook: Models::Shared::Webhook).void }
        def initialize(id: nil, webhook: nil)
          @id = id
          @webhook = webhook
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @webhook == other.webhook
          true
        end
      end
    end
  end
end
