workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://api.unified.to/openapi.json
              authSecret: $openapi_doc_auth_token
targets:
    ruby-target:
        target: ruby
        source: my-source
