workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api.unified.to/openapi.json
              authSecret: $openapi_doc_auth_token
        registry:
            location: registry.speakeasyapi.dev/unified/unified/my-source
targets:
    ruby-target:
        target: ruby
        source: my-source
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/unified/unified/my-source-ruby-code-samples
            blocking: false
