"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OrderType(str, Enum):
    r"""The type of order."""
    DRINK = 'drink'
    INGREDIENT = 'ingredient'
