name: Generate
permissions:
    checks: write
    contents: write
    pull-requests: write
    statuses: write
"on":
    workflow_dispatch:
        inputs:
            force:
                description: Force generation of SDKs
                type: boolean
                default: false
    schedule:
        - cron: 0 0 * * *
jobs:
    generate:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
        with:
            force: ${{ github.event.inputs.force }}
            mode: direct
            speakeasy_version: latest
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            openapi_doc_auth_token: ${{ secrets.SPEC_TOKEN }}
            slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
